# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-25 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171221_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='image/1.jpg', upload_to='image/%Y/%m', verbose_name='主照片'),
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(default='images/1.jpg', upload_to='images/%Y/%m', verbose_name='详细照片'),
        ),
    ]
